apiVersion: skaffold/v4beta11
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  # Local build
  # local:
  #   push: false
  # Google Cloud Build
  googleCloudBuild:
    projectId: ticketing-dev-440705
  artifacts:
    - image: gcr.io/ticketing-dev-440705/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: gcr.io/ticketing-dev-440705/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.tsx"
            dest: .
    - image: gcr.io/ticketing-dev-440705/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
